testBicitme/config/routes.rb
Rails.application.routes.draw do
  resources :denuncia
  resources :robos
  resources :presupuestos
  get 'registrarpresupuesto', to: 'presupuestos#new', as: 'registrarpresupuesto'
  get 'editarpresupuesto', to: 'presupuestos#index', as: 'editarpresupuesto'
  resources :reparacions
  get 'registrarreparacion', to: 'reparacions#new', as: 'registrarreparacion'
  get 'editarreparacion', to: 'reparacions#index', as: 'editarreparacion'
  resources :calificacions
  get 'registrarcalificacion', to: 'calificacions#new', as: 'registrarcalificacion'
  get 'editarcalificacion', to: 'calificacions#index', as: 'editarcalificacion'
  resources :postulacions
  get 'registrarpostulacion', to: 'postulacions#new', as: 'registrarpostulacion'
  get 'editarpostulacion', to: 'postulacions#index', as: 'editarpostulacion'
  resources :tallers
  get 'registrartaller', to: 'tallers#new', as: 'registrartaller'
  get 'editartaller', to: 'tallers#index', as: 'editartaller'
  resources :comunas
  get 'registrarcomuna', to: 'comunas#new', as: 'registrarcomuna'
  get 'editarcomuna', to: 'comunas#index', as: 'editarcomuna'
  resources :administradors
  get 'bienvenida', to: 'administradors#new', as: 'bienvenida'
  resources :encargado_tallers
  get 'registrarenc', to: 'encargado_tallers#new', as: 'registrarenc'
  get 'editarenc', to: 'encargado_tallers#index', as: 'editarenc'
  resources :ciclista
  get 'registrartelf', to: 'ciclista#new', as: 'registrartelf'
  get 'editartelf', to: 'ciclista#index', as: 'editartelf'
  get 'vista/index'
  get 'vista/ciclista'
  get 'vista/taller'
  root 'vista#index'
  get '/' => 'vista#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :bicicleta
  resources :usuarios
end

testBicitme/app/models/administrador.rb
class Administrador < ActiveRecord::Base
end

testBicitme/app/models/bicicletum.rb
class Bicicletum < ActiveRecord::Base
	belongs_to :Ciclista
	def combined_value
    "Marca: #{self.bic_marca} Modelo: #{self.bic_modelo} Color: #{self.bic_color_princ}"
  end
end

testBicitme/app/models/calificacion.rb
class Calificacion < ActiveRecord::Base
end

testBicitme/app/models/ciclistum.rb
class Ciclistum < ActiveRecord::Base
	belongs_to :Usuario
	has_many :Bicicletum
end

testBicitme/app/models/comuna.rb
class Comuna < ActiveRecord::Base
end

testBicitme/app/models/denuncium.rb
class Denuncium < ActiveRecord::Base
end

testBicitme/app/models/encargado_taller.rb
class EncargadoTaller < ActiveRecord::Base
   belongs_to :Usuario
end

testBicitme/app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
end

testBicitme/app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
end

testBicitme/app/models/reparacion.rb
class Reparacion < ActiveRecord::Base
  
  def mostrar_combinado
    "Comentario: #{self.rep_comentario} Direccion: #{self.rep_direccion} Fecha: #{self.rep_fecha_in}"
  end
end

testBicitme/app/models/robo.rb
class Robo < ActiveRecord::Base
end

testBicitme/app/models/taller.rb
class Taller < ActiveRecord::Base
end

testBicitme/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :Ciclistum
	has_many :Encargado_taller
end

testBicitme/app/controllers/tallers_controller.rb
class TallersController < ApplicationController
  before_action :set_taller, only: [:show, :edit, :update, :destroy]

  # GET /tallers
  # GET /tallers.json
  def index
    @tallers = Taller.where(:encargado_id => current_user.id)
  end

  # GET /tallers/1
  # GET /tallers/1.json
  def show
  end

  # GET /tallers/new
  def new
    @taller = Taller.new
  end

  # GET /tallers/1/edit
  def edit
  end

  # POST /tallers
  # POST /tallers.json
  def create
    @taller = Taller.new(taller_params)
    @taller.encargado_id = current_user.id
    @taller.taller_estado = 'Inactivo'
    @taller.taller_cant_den = 0
    @taller.taller_cant_cont_den = 0
    @taller.taller_calificacion = 0
    respond_to do |format|
      if  Taller.where(:encargado_id => current_user.id).count == 0
        
          if @taller.save
            format.html { redirect_to @taller, notice: 'Taller was successfully created.' }
            format.json { render :show, status: :created, location: @taller }
          else
            format.html { render :new }
            format.json { render json: @taller.errors, status: :unprocessable_entity }
          end
        
        else
          format.html { redirect_to vista_taller_path, notice: 'Taller no puede ser creado, ya ha creado uno.' }
          format.json { render json: @taller.errors, status: :unprocessable_entity }
       end
     end
  end

  # PATCH/PUT /tallers/1
  # PATCH/PUT /tallers/1.json
  def update
    respond_to do |format|
      if @taller.update(taller_params)
        format.html { redirect_to @taller, notice: 'Taller was successfully updated.' }
        format.json { render :show, status: :ok, location: @taller }
      else
        format.html { render :edit }
        format.json { render json: @taller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tallers/1
  # DELETE /tallers/1.json
  def destroy
    @taller.destroy
    respond_to do |format|
      format.html { redirect_to tallers_url, notice: 'Taller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taller
      @taller = Taller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taller_params
      params.require(:taller).permit(:taller_nombre, :taller_patente, :taller_direccion, :taller_web_page, :taller_cant_den, :taller_cant_cont_den, :taller_descripcion, :taller_calificacion, :taller_fono, :taller_estado, :comuna_id, :encargado_id)
    end
end

testBicitme/app/helpers/bicicleta_helper.rb
module BicicletaHelper
end

testBicitme/app/helpers/ciclista_helper.rb
module CiclistaHelper
end

testBicitme/app/helpers/comunas_helper.rb
module ComunasHelper
end

testBicitme/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

testBicitme/app/helpers/robos_helper.rb
module RobosHelper
end

testBicitme/app/helpers/sessions_helper.rb
module SessionsHelper
end

testBicitme/app/helpers/tallers_helper.rb
module TallersHelper
end

testBicitme/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

testBicitme/app/helpers/vista_helper.rb
module VistaHelper
end

testBicitme/app/views/tallers/_editar.html.erb
<%= form_for(@taller) do |f| %>
  <% if @taller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taller.errors.count, "error") %> prohibited this taller from being saved:</h2>

      <ul>
      <% @taller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :taller_web_page %><br>
    <%= f.text_field :taller_web_page %>
  </div>
  
  <div class="field">
    <%= f.label :taller_descripcion %><br>
    <%= f.text_field :taller_descripcion %>
  </div>
  
  <div class="field">
    <%= f.label :taller_fono %><br>
    <%= f.text_field :taller_fono %>
  </div>
  <!--<div class="field">
    <%= f.label :taller_estado %><br>
    <%= f.text_field :taller_estado %>
  </div>
  <div class="field">
    <%= f.label :taller_cant_den %><br>
    <%= f.number_field :taller_cant_den %>
  </div>
  <div class="field">
    <%= f.label :taller_cant_cont_den %><br>
    <%= f.number_field :taller_cant_cont_den %>
  </div>
  <div class="field">
    <%= f.label :taller_calificacion %><br>
    <%= f.text_field :taller_calificacion %>
  </div>
  <div class="field">
    <%= f.label :encargado_id %><br>
    <%= f.number_field :encargado_id %>
  </div>-->
  <div class="actions">
    <%= f.submit "Confimar"%>
  </div>
<% end %>

testBicitme/app/views/tallers/_form.html.erb
<%= form_for(@taller) do |f| %>
  <% if @taller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taller.errors.count, "error") %> prohibited this taller from being saved:</h2>

      <ul>
      <% @taller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :taller_nombre %><br>
    <%= f.text_field :taller_nombre %>
  </div>
  <div class="field">
    <%= f.label :taller_patente %><br>
    <%= f.text_field :taller_patente %>
  </div>
  <div class="field">
    <%= f.label :taller_direccion %><br>
    <%= f.text_field :taller_direccion %>
  </div>
  <div class="field">
    <%= f.label :taller_web_page %><br>
    <%= f.text_field :taller_web_page %>
  </div>
  
  <div class="field">
    <%= f.label :taller_descripcion %><br>
    <%= f.text_field :taller_descripcion %>
  </div>
  
  <div class="field">
    <%= f.label :taller_fono %><br>
    <%= f.text_field :taller_fono %>
  </div>
  <div class="field">
    <%= f.label :comuna_id %><br>
    <%= f.collection_select :comuna_id, Comuna.all, :id, :com_nombre %>
  </div>
  <!--<div class="field">
    <%= f.label :taller_estado %><br>
    <%= f.text_field :taller_estado %>
  </div>
  <div class="field">
    <%= f.label :taller_cant_den %><br>
    <%= f.number_field :taller_cant_den %>
  </div>
  <div class="field">
    <%= f.label :taller_cant_cont_den %><br>
    <%= f.number_field :taller_cant_cont_den %>
  </div>
  <div class="field">
    <%= f.label :taller_calificacion %><br>
    <%= f.text_field :taller_calificacion %>
  </div>
  <div class="field">
    <%= f.label :encargado_id %><br>
    <%= f.number_field :encargado_id %>
  </div>-->
  <div class="actions">
    <%= f.submit "Confimar"%>
  </div>
<% end %>

testBicitme/app/views/tallers/edit.html.erb
<h1>Editing Taller</h1>

<%= render 'editar' %>

<!--<%= link_to 'Show', @taller %> |
<%= link_to 'Back', tallers_path %>-->

testBicitme/app/views/tallers/index.html.erb
 

<h1>Listing Tallers</h1>

<table>
  <thead>
    <tr>
      <th>Taller nombre</th>
      <th>Taller patente</th>
      <th>Taller direccion</th>
      <th>Taller web page</th>
      <th>Taller cant den</th>
      <th>Taller cant cont den</th>
      <th>Taller descripcion</th>
      <th>Taller calificacion</th>
      <th>Taller fono</th>
      <!--<th>Taller estado</th> 
      <th>Comuna</th>
      <th>Encargado</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tallers.each do |taller| %>
      <tr>
        <td><%= taller.taller_nombre %></td>
        <td><%= taller.taller_patente %></td>
        <td><%= taller.taller_direccion %></td>
        <td><%= taller.taller_web_page %></td>
        <td><%= taller.taller_cant_den %></td>
        <td><%= taller.taller_cant_cont_den %></td>
        <td><%= taller.taller_descripcion %></td>
        <td><%= taller.taller_calificacion %></td>
        <td><%= taller.taller_fono %></td>
        <!--<td><%= taller.taller_estado %></td>
        <td><%= taller.comuna_id %></td>
        <td><%= taller.encargado_id %></td>-->
        <!--<td><%= link_to 'Show', taller %></td>-->
        <td><%= link_to 'Actualizar Telefono y/o Web page', edit_taller_path(taller) %></td>
        <!--<td><%= link_to 'Destroy', taller, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Taller', new_taller_path %>-->

testBicitme/app/views/tallers/new.html.erb
<h1>New Taller</h1>

<%= render 'form' %>

<%= link_to 'Back', tallers_path %>

testBicitme/app/views/tallers/show.html.erb
 

<p>
  <strong>Taller nombre:</strong>
  <%= @taller.taller_nombre %>
</p>

<p>
  <strong>Taller patente:</strong>
  <%= @taller.taller_patente %>
</p>

<p>
  <strong>Taller direccion:</strong>
  <%= @taller.taller_direccion %>
</p>

<p>
  <strong>Taller web page:</strong>
  <%= @taller.taller_web_page %>
</p>

<p>
  <strong>Taller cant den:</strong>
  <%= @taller.taller_cant_den %>
</p>

<p>
  <strong>Taller cant cont den:</strong>
  <%= @taller.taller_cant_cont_den %>
</p>

<p>
  <strong>Taller descripcion:</strong>
  <%= @taller.taller_descripcion %>
</p>

<p>
  <strong>Taller calificacion:</strong>
  <%= @taller.taller_calificacion %>
</p>

<p>
  <strong>Taller fono:</strong>
  <%= @taller.taller_fono %>
</p>

<p>
  <strong>Taller estado:</strong>
  <%= @taller.taller_estado %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @taller.comuna_id %>
</p>
<%if  !Postulacion.where(:encargado_id => current_user.id, :post_estado => ["Espera","Activo"]).count == 0%>
	<%= link_to 'Registrar postulacion', registrarpostulacion_path %>
<%end%>
<!--<p>
  <strong>Encargado id:</strong>
  <%= @taller.encargado_id %>
</p>


<!--<%= link_to 'Back', tallers_path %>-->