testBicitme/config/routes.rb
Rails.application.routes.draw do
  resources :denuncia
  resources :robos
  resources :presupuestos
  get 'registrarpresupuesto', to: 'presupuestos#new', as: 'registrarpresupuesto'
  get 'editarpresupuesto', to: 'presupuestos#index', as: 'editarpresupuesto'
  resources :reparacions
  get 'registrarreparacion', to: 'reparacions#new', as: 'registrarreparacion'
  get 'editarreparacion', to: 'reparacions#index', as: 'editarreparacion'
  resources :calificacions
  get 'registrarcalificacion', to: 'calificacions#new', as: 'registrarcalificacion'
  get 'editarcalificacion', to: 'calificacions#index', as: 'editarcalificacion'
  resources :postulacions
  get 'registrarpostulacion', to: 'postulacions#new', as: 'registrarpostulacion'
  get 'editarpostulacion', to: 'postulacions#index', as: 'editarpostulacion'
  resources :tallers
  get 'registrartaller', to: 'tallers#new', as: 'registrartaller'
  get 'editartaller', to: 'tallers#index', as: 'editartaller'
  resources :comunas
  get 'registrarcomuna', to: 'comunas#new', as: 'registrarcomuna'
  get 'editarcomuna', to: 'comunas#index', as: 'editarcomuna'
  resources :administradors
  get 'bienvenida', to: 'administradors#new', as: 'bienvenida'
  resources :encargado_tallers
  get 'registrarenc', to: 'encargado_tallers#new', as: 'registrarenc'
  get 'editarenc', to: 'encargado_tallers#index', as: 'editarenc'
  resources :ciclista
  get 'registrartelf', to: 'ciclista#new', as: 'registrartelf'
  get 'editartelf', to: 'ciclista#index', as: 'editartelf'
  get 'vista/index'
  get 'vista/ciclista'
  get 'vista/taller'
  root 'vista#index'
  get '/' => 'vista#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :bicicleta
  resources :usuarios
end

testBicitme/app/models/administrador.rb
class Administrador < ActiveRecord::Base
end

testBicitme/app/models/bicicletum.rb
class Bicicletum < ActiveRecord::Base
	belongs_to :Ciclista
	def combined_value
    "Marca: #{self.bic_marca} Modelo: #{self.bic_modelo} Color: #{self.bic_color_princ}"
  end
end

testBicitme/app/models/calificacion.rb
class Calificacion < ActiveRecord::Base
end

testBicitme/app/models/ciclistum.rb
class Ciclistum < ActiveRecord::Base
	belongs_to :Usuario
	has_many :Bicicletum
end

testBicitme/app/models/comuna.rb
class Comuna < ActiveRecord::Base
end

testBicitme/app/models/denuncium.rb
class Denuncium < ActiveRecord::Base
end

testBicitme/app/models/encargado_taller.rb
class EncargadoTaller < ActiveRecord::Base
   belongs_to :Usuario
end

testBicitme/app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
end

testBicitme/app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
end

testBicitme/app/models/reparacion.rb
class Reparacion < ActiveRecord::Base
  
  def mostrar_combinado
    "Comentario: #{self.rep_comentario} Direccion: #{self.rep_direccion} Fecha: #{self.rep_fecha_in}"
  end
end

testBicitme/app/models/robo.rb
class Robo < ActiveRecord::Base
end

testBicitme/app/models/taller.rb
class Taller < ActiveRecord::Base
end

testBicitme/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :Ciclistum
	has_many :Encargado_taller
end

testBicitme/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json

  def index
    @usuarios = Usuario.all
    @bicicletas = Bicicletum.all 
    @ciclista = Ciclistum.all 
  end
  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    if (current_user) #Quien lo está creando es un admin? -> el usuario que va a crear también lo es.
      @usuario.usuar_tipo_cod = 'A'
    end
    respond_to do |format|
      if @usuario.save
        if (current_user) #Ya esta dentro del sistema?
        else
          session[:usuarios_id] = @usuario.id #si no lo esta ingresarlo.  
        end
        
        format.html { redirect_to @usuario, notice: 'Usuario creado con exito.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario actualizado.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:usuar_run, :usuar_ap_pat, :usuar_ap_mat, :usuar_nom_usuario, :usuar_contrasegna, :usuar_correo, :usuar_tipo_cod)
    end
end

testBicitme/app/helpers/bicicleta_helper.rb
module BicicletaHelper
end

testBicitme/app/helpers/ciclista_helper.rb
module CiclistaHelper
end

testBicitme/app/helpers/comunas_helper.rb
module ComunasHelper
end

testBicitme/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

testBicitme/app/helpers/robos_helper.rb
module RobosHelper
end

testBicitme/app/helpers/sessions_helper.rb
module SessionsHelper
end

testBicitme/app/helpers/tallers_helper.rb
module TallersHelper
end

testBicitme/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

testBicitme/app/helpers/vista_helper.rb
module VistaHelper
end

testBicitme/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2> No se pudo completar la tarea.</h2>
    </div>
  <% end %>
    


  <div class="field">
    <%= f.label :"Ingrese RUN:" %><br>
    <%= f.text_field :usuar_run, class:"form-control", required: true %>
  </div>
    <div class="field">
    <%= f.label :"Ingrese Nombre:" %><br>
    <%= f.text_field :usuar_nom_usuario, class:"form-control", required: true  %>
  </div>
  <div class="field">
    <%= f.label :"Ingrese Apellido Paterno:"%><br>
    <%= f.text_field :usuar_ap_pat, class:"form-control", required: true %>
  </div>
  <div class="field">
    <%= f.label :"Ingrese Apellido Materno:"%><br>
    <%= f.text_field :usuar_ap_mat, class:"form-control", required: true %>
  </div>

 
  <div class="field">
    <%= f.label :"Ingrese una contraseña:" %><br>
    <%= f.text_field :usuar_contrasegna, class:"form-control", required: true %>
  </div>
  <div class="field">
    <%= f.label :"Ingrese su correo:" %><br>
    <%= f.text_field :usuar_correo, class:"form-control", required: true %>
  </div>
  <% if current_user %>			<!-- HACERLO MAS BONITO, QUE SE NOTE QUE SE ESTÁ REGISTRANDO UN ADMIN-->
  <% else %>
  <div class="field">
  <%= f.label :"Usted es un Ciclista o un Taller:" %><br>
    <%= f.radio_button(:usuar_tipo_cod, "C", :checked => true) %>
    <%= f.label(:usuar_tipo_cod, "Ciclista") %><br>
    <%= f.radio_button(:usuar_tipo_cod, "E") %>
    <%= f.label(:usuar_tipo_cod, "Encargado") %>
  </div>
  <% end %>
<br>
  <div class="actions">
    <%= f.submit "Crear Cuenta", class:"btn btn-success"%>
  </div>
<% end %>

testBicitme/app/views/usuarios/edit.html.erb
<div class="center jumbotron">
<h1>Editar Usuario</h1>
<%= render 'form' %>
</div>

testBicitme/app/views/usuarios/index.html.erb
 

<h1>Lista de Usuarios</h1>

<table>
  <thead>
    <tr>
      <th> Run</th>
      <th> Apellido Paterno</th>
      <th> Apellido Materno</th>
      <th> Nombre de Usuario</th>
      <th> Contraseña</th>
      <th> Correo</th>
      <th> Tipo Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.usuar_run %></td>
        <td><%= usuario.usuar_ap_pat %></td>
        <td><%= usuario.usuar_ap_mat %></td>
        <td><%= usuario.usuar_nom_usuario %></td>
        <td><%= usuario.usuar_contrasegna %></td>
        <td><%= usuario.usuar_correo %></td>
        <td><%= usuario.usuar_tipo_cod %></td>
        <td><%= link_to 'Mostrar', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: '¿Esta seguro/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
<%= link_to 'Ver Bicicletas registradas', bicicleta_path %>
<% end %>

testBicitme/app/views/usuarios/login.html.erb
<%= form_for(:session, url: sessions_path) do |f| %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label "Remember me" %>			<!-- REVISAR NO SE MUESTRA EN EL SISTEMA -->
  <%= f.check_box :remember_session %>

  <%= f.submit "Iniciar sesión" %>
<% end %>

testBicitme/app/views/usuarios/new.html.erb
<h1>Crear Usuario</h1>

<h2><%= render 'form' %></h2>

testBicitme/app/views/usuarios/show.html.erb
<h1>Usuario Creado:<h1>
<p>
  <strong>Run:</strong>
  <%= @usuario.usuar_run %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= @usuario.usuar_nom_usuario %>
</p>
<p>
  <strong>Apellido Paterno:</strong>
  <%= @usuario.usuar_ap_pat %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @usuario.usuar_ap_mat %>
</p>

<p>
  <strong>Correo Electronico:</strong>
  <%= @usuario.usuar_correo %>
</p>
<p>
  <strong>Cuenta tipo:</strong>
  <%if @usuario.usuar_tipo_cod == 'C' %>
  	Ciclista
  <%else %>
  	<% if @usuario.usuar_tipo_cod == 'E'%>
  		Encargado
  	<%else%>
  		Administrador
  	<% end %>
  <%end %>
</p>

<%= link_to 'Editar Informacion', edit_usuario_path(@usuario), class:"btn btn-lg btn-info" %> |
<%if @usuario.usuar_tipo_cod == "C"%>
<%= link_to 'Debe continuar su registro', registrartelf_path, class:"btn btn-lg btn-success" %>
<!--<%= link_to 'Siguiente', vista_ciclista_path, class:"btn btn-lg btn-success" %>-->
<%else%>
	<% if @usuario.usuar_tipo_cod == 'E'%>
		<%= link_to 'Debe continuar su registro', registrarenc_path, class:"btn btn-lg btn-success" %>
		<!--<%= link_to 'Siguiente', vista_taller_path, class:"btn btn-lg btn-success" %>  <!-- DEBERIA IR DE MANERA OBLIGATORIA A TERMINAR SU REGISTRO -->
	<%else%>
		<!-- AGREGAR ACCIONES PARA ADMIN-->
	<%end%>

<%end%>