testBicitme/config/routes.rb
Rails.application.routes.draw do
  resources :denuncia
  resources :robos
  resources :presupuestos
  get 'registrarpresupuesto', to: 'presupuestos#new', as: 'registrarpresupuesto'
  get 'editarpresupuesto', to: 'presupuestos#index', as: 'editarpresupuesto'
  resources :reparacions
  get 'registrarreparacion', to: 'reparacions#new', as: 'registrarreparacion'
  get 'editarreparacion', to: 'reparacions#index', as: 'editarreparacion'
  resources :calificacions
  get 'registrarcalificacion', to: 'calificacions#new', as: 'registrarcalificacion'
  get 'editarcalificacion', to: 'calificacions#index', as: 'editarcalificacion'
  resources :postulacions
  get 'registrarpostulacion', to: 'postulacions#new', as: 'registrarpostulacion'
  get 'editarpostulacion', to: 'postulacions#index', as: 'editarpostulacion'
  resources :tallers
  get 'registrartaller', to: 'tallers#new', as: 'registrartaller'
  get 'editartaller', to: 'tallers#index', as: 'editartaller'
  resources :comunas
  get 'registrarcomuna', to: 'comunas#new', as: 'registrarcomuna'
  get 'editarcomuna', to: 'comunas#index', as: 'editarcomuna'
  resources :administradors
  get 'bienvenida', to: 'administradors#new', as: 'bienvenida'
  resources :encargado_tallers
  get 'registrarenc', to: 'encargado_tallers#new', as: 'registrarenc'
  get 'editarenc', to: 'encargado_tallers#index', as: 'editarenc'
  resources :ciclista
  get 'registrartelf', to: 'ciclista#new', as: 'registrartelf'
  get 'editartelf', to: 'ciclista#index', as: 'editartelf'
  get 'vista/index'
  get 'vista/ciclista'
  get 'vista/taller'
  root 'vista#index'
  get '/' => 'vista#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :bicicleta
  resources :usuarios
end

testBicitme/app/models/administrador.rb
class Administrador < ActiveRecord::Base
end

testBicitme/app/models/bicicletum.rb
class Bicicletum < ActiveRecord::Base
	belongs_to :Ciclista
	def combined_value
    "Marca: #{self.bic_marca} Modelo: #{self.bic_modelo} Color: #{self.bic_color_princ}"
  end
end

testBicitme/app/models/calificacion.rb
class Calificacion < ActiveRecord::Base
end

testBicitme/app/models/ciclistum.rb
class Ciclistum < ActiveRecord::Base
	belongs_to :Usuario
	has_many :Bicicletum
end

testBicitme/app/models/comuna.rb
class Comuna < ActiveRecord::Base
end

testBicitme/app/models/denuncium.rb
class Denuncium < ActiveRecord::Base
end

testBicitme/app/models/encargado_taller.rb
class EncargadoTaller < ActiveRecord::Base
   belongs_to :Usuario
end

testBicitme/app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
end

testBicitme/app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
end

testBicitme/app/models/reparacion.rb
class Reparacion < ActiveRecord::Base
  
  def mostrar_combinado
    "Comentario: #{self.rep_comentario} Direccion: #{self.rep_direccion} Fecha: #{self.rep_fecha_in}"
  end
end

testBicitme/app/models/robo.rb
class Robo < ActiveRecord::Base
end

testBicitme/app/models/taller.rb
class Taller < ActiveRecord::Base
end

testBicitme/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :Ciclistum
	has_many :Encargado_taller
end

testBicitme/app/controllers/comunas_controller.rb
class ComunasController < ApplicationController
  before_action :set_comuna, only: [:show, :edit, :update, :destroy]

  # GET /comunas
  # GET /comunas.json
  def index
    @comunas = Comuna.all
  end

  # GET /comunas/1
  # GET /comunas/1.json
  def show
  end

  # GET /comunas/new
  def new
    @comuna = Comuna.new
  end

  # GET /comunas/1/edit
  def edit
  end

  # POST /comunas
  # POST /comunas.json
  def create
    @comuna = Comuna.new(comuna_params)

    respond_to do |format|
      if @comuna.save
        format.html { redirect_to @comuna, notice: 'Comuna was successfully created.' }
        format.json { render :show, status: :created, location: @comuna }
      else
        format.html { render :new }
        format.json { render json: @comuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comunas/1
  # PATCH/PUT /comunas/1.json
  def update
    respond_to do |format|
      if @comuna.update(comuna_params)
        format.html { redirect_to @comuna, notice: 'Comuna was successfully updated.' }
        format.json { render :show, status: :ok, location: @comuna }
      else
        format.html { render :edit }
        format.json { render json: @comuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comunas/1
  # DELETE /comunas/1.json
  def destroy
    @comuna.destroy
    respond_to do |format|
      format.html { redirect_to comunas_url, notice: 'Comuna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comuna
      @comuna = Comuna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comuna_params
      params.require(:comuna).permit(:com_nombre)
    end
end

testBicitme/app/helpers/bicicleta_helper.rb
module BicicletaHelper
end

testBicitme/app/helpers/ciclista_helper.rb
module CiclistaHelper
end

testBicitme/app/helpers/comunas_helper.rb
module ComunasHelper
end

testBicitme/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

testBicitme/app/helpers/robos_helper.rb
module RobosHelper
end

testBicitme/app/helpers/sessions_helper.rb
module SessionsHelper
end

testBicitme/app/helpers/tallers_helper.rb
module TallersHelper
end

testBicitme/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

testBicitme/app/helpers/vista_helper.rb
module VistaHelper
end

testBicitme/app/views/comunas/_form.html.erb
<%= form_for(@comuna) do |f| %>
  <% if @comuna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comuna.errors.count, "error") %> prohibited this comuna from being saved:</h2>

      <ul>
      <% @comuna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :com_nombre %><br>
    <%= f.text_field :com_nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testBicitme/app/views/comunas/edit.html.erb
<h1>Editing Comuna</h1>

<%= render 'form' %>

<%= link_to 'Show', @comuna %> |
<%= link_to 'Back', comunas_path %>

testBicitme/app/views/comunas/index.html.erb
 

<h1>Listing Comunas</h1>

<table>
  <thead>
    <tr>
      <th>Com nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comunas.each do |comuna| %>
      <tr>
        <td><%= comuna.com_nombre %></td>
        <td><%= link_to 'Show', comuna %></td>
        <td><%= link_to 'Edit', edit_comuna_path(comuna) %></td>
        <td><%= link_to 'Destroy', comuna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comuna', new_comuna_path %>

testBicitme/app/views/comunas/new.html.erb
<h1>New Comuna</h1>

<%= render 'form' %>

<%= link_to 'Back', comunas_path %>

testBicitme/app/views/comunas/show.html.erb
 

<p>
  <strong>Com nombre:</strong>
  <%= @comuna.com_nombre %>
</p>

<%= link_to 'Edit', edit_comuna_path(@comuna) %> |
<%= link_to 'Back', comunas_path %>