testBicitme/config/routes.rb
Rails.application.routes.draw do
  resources :denuncia
  resources :robos
  resources :presupuestos
  get 'registrarpresupuesto', to: 'presupuestos#new', as: 'registrarpresupuesto'
  get 'editarpresupuesto', to: 'presupuestos#index', as: 'editarpresupuesto'
  resources :reparacions
  get 'registrarreparacion', to: 'reparacions#new', as: 'registrarreparacion'
  get 'editarreparacion', to: 'reparacions#index', as: 'editarreparacion'
  resources :calificacions
  get 'registrarcalificacion', to: 'calificacions#new', as: 'registrarcalificacion'
  get 'editarcalificacion', to: 'calificacions#index', as: 'editarcalificacion'
  resources :postulacions
  get 'registrarpostulacion', to: 'postulacions#new', as: 'registrarpostulacion'
  get 'editarpostulacion', to: 'postulacions#index', as: 'editarpostulacion'
  resources :tallers
  get 'registrartaller', to: 'tallers#new', as: 'registrartaller'
  get 'editartaller', to: 'tallers#index', as: 'editartaller'
  resources :comunas
  get 'registrarcomuna', to: 'comunas#new', as: 'registrarcomuna'
  get 'editarcomuna', to: 'comunas#index', as: 'editarcomuna'
  resources :administradors
  get 'bienvenida', to: 'administradors#new', as: 'bienvenida'
  resources :encargado_tallers
  get 'registrarenc', to: 'encargado_tallers#new', as: 'registrarenc'
  get 'editarenc', to: 'encargado_tallers#index', as: 'editarenc'
  resources :ciclista
  get 'registrartelf', to: 'ciclista#new', as: 'registrartelf'
  get 'editartelf', to: 'ciclista#index', as: 'editartelf'
  get 'vista/index'
  get 'vista/ciclista'
  get 'vista/taller'
  root 'vista#index'
  get '/' => 'vista#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :bicicleta
  resources :usuarios
end

testBicitme/app/models/administrador.rb
class Administrador < ActiveRecord::Base
end

testBicitme/app/models/bicicletum.rb
class Bicicletum < ActiveRecord::Base
	belongs_to :Ciclista
	def combined_value
    "Marca: #{self.bic_marca} Modelo: #{self.bic_modelo} Color: #{self.bic_color_princ}"
  end
end

testBicitme/app/models/calificacion.rb
class Calificacion < ActiveRecord::Base
end

testBicitme/app/models/ciclistum.rb
class Ciclistum < ActiveRecord::Base
	belongs_to :Usuario
	has_many :Bicicletum
end

testBicitme/app/models/comuna.rb
class Comuna < ActiveRecord::Base
end

testBicitme/app/models/denuncium.rb
class Denuncium < ActiveRecord::Base
end

testBicitme/app/models/encargado_taller.rb
class EncargadoTaller < ActiveRecord::Base
   belongs_to :Usuario
end

testBicitme/app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
end

testBicitme/app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
end

testBicitme/app/models/reparacion.rb
class Reparacion < ActiveRecord::Base
  
  def mostrar_combinado
    "Comentario: #{self.rep_comentario} Direccion: #{self.rep_direccion} Fecha: #{self.rep_fecha_in}"
  end
end

testBicitme/app/models/robo.rb
class Robo < ActiveRecord::Base
end

testBicitme/app/models/taller.rb
class Taller < ActiveRecord::Base
end

testBicitme/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :Ciclistum
	has_many :Encargado_taller
end

testBicitme/app/controllers/postulacions_controller.rb
class PostulacionsController < ApplicationController
  before_action :set_postulacion, only: [:show, :edit, :update, :destroy]

  # GET /postulacions
  # GET /postulacions.json
  def index
    @postulacions = Postulacion.all
  end

  # GET /postulacions/1
  # GET /postulacions/1.json
  def show
  end

  # GET /postulacions/new
  def new
    @postulacion = Postulacion.new
  end

  # GET /postulacions/1/edit
  def edit
  end

  # POST /postulacions
  # POST /postulacions.json
  def create
    @postulacion = Postulacion.new(postulacion_params)    
    @postulacion.encargado_id = current_user.id
    @postulacion.post_estado = "Espera"
    respond_to do |format|
      if  Postulacion.where(:encargado_id => current_user.id, :post_estado => ["Espera","Activo"]).count == 0
        if Taller.where(:encargado_id => current_user.id).count == 0
          format.html { redirect_to vista_taller_path, notice: 'Postulación no puede ser creada, no posee un taller' }
          format.json { render json: @taller.errors, status: :unprocessable_entity }
        else
          if @postulacion.save
            format.html { redirect_to @postulacion, notice: 'Postulacion was successfully created.' }
            format.json { render :show, status: :created, location: @postulacion }
          else
            format.html { render :new }
            format.json { render json: @postulacion.errors, status: :unprocessable_entity }
          end
        end
      else
        format.html { redirect_to vista_taller_path, notice: 'Postulación no puede ser creada, ya tiene una en espera o ya tiene un taller aceptado' }
        format.json { render json: @taller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postulacions/1
  # PATCH/PUT /postulacions/1.json
  def update      #EDITAR PARA AGREGAR QUE EL ADMIN EDITE
    
    
    respond_to do |format|
      if @postulacion.update(postulacion_params)
        if (@postulacion.post_estado == 'Activo')
          Taller.where(:encargado_id => @postulacion.encargado_id).update_all(:taller_estado => 'Activo')
          Administrador.where(:usuario_id => current_user.id).update_all("admin_cant_aceptados = admin_cant_aceptados + 1") #(:admin_cant_aceptados => (:admin_cant_aceptados + 1))
        end
        format.html { redirect_to @postulacion, notice: 'Postulacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @postulacion }
      else
        format.html { render :edit }
        format.json { render json: @postulacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postulacions/1
  # DELETE /postulacions/1.json
  def destroy
    @postulacion.destroy
    respond_to do |format|
      format.html { redirect_to postulacions_url, notice: 'Postulacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postulacion
      @postulacion = Postulacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postulacion_params
      params.require(:postulacion).permit(:post_tiempo_taller, :post_referencia_1, :post_referencia_2, :post_estado, :encargado_id, :administrador_id)
    end
end

testBicitme/app/helpers/ciclista_helper.rb
module CiclistaHelper
end

testBicitme/app/helpers/comunas_helper.rb
module ComunasHelper
end

testBicitme/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

testBicitme/app/helpers/postulacions_helper.rb
module PostulacionsHelper
end

testBicitme/app/helpers/robos_helper.rb
module RobosHelper
end

testBicitme/app/helpers/sessions_helper.rb
module SessionsHelper
end

testBicitme/app/helpers/tallers_helper.rb
module TallersHelper
end

testBicitme/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

testBicitme/app/helpers/vista_helper.rb
module VistaHelper
end

testBicitme/app/views/postulacions/_form.html.erb
<%= form_for(@postulacion) do |f| %>
  <% if @postulacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postulacion.errors.count, "error") %> prohibited this postulacion from being saved:</h2>

      <ul>
      <% @postulacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user.usuar_tipo_cod == 'A'%>
  <div class="field">
    <%= f.label :post_tiempo_taller %><br>
    <%= @postulacion.post_tiempo_taller %>
  </div>
  <div class="field">
    <%= f.label :post_referencia_1 %><br>
    <%= @postulacion.post_referencia_1 %>
  </div>
  <div class="field">
    <%= f.label :post_referencia_2 %><br>
    <%= @postulacion.post_referencia_2 %>
  </div>
  <div class="field">
	<%= f.label :"Tipo Estado:" %><br>
    <%= f.radio_button(:post_estado , "Espera") %>
    <%= f.label(:post_estado , "Espera") %><br>
    <%= f.radio_button(:post_estado , "Activo") %>
	<%= f.label(:post_estado ,"Activo" ) %><br>
	 <%= f.radio_button(:post_estado , "Rechazado") %>
	<%= f.label(:post_estado ,"Rechazado" ) %><br>
  </div>
  <div class="field">
    <%= f.label :encargado_id %><br>
    <%= @postulacion.encargado_id %>
  </div>
  <%else%>
  <div class="field">
    <%= f.label :post_tiempo_taller %><br>
    <%= f.text_field :post_tiempo_taller %>
  </div>
  <div class="field">
    <%= f.label :post_referencia_1 %><br>
    <%= f.text_field :post_referencia_1 %>
  </div>
  <div class="field">
    <%= f.label :post_referencia_2 %><br>
    <%= f.text_field :post_referencia_2 %>
  </div>
  <%end%>
  <!--
  <div class="field">
    <%= f.label :administrador_id %><br>
    <%= f.number_field :administrador_id %>
  </div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testBicitme/app/views/postulacions/edit.html.erb
<h1>Editing Postulacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @postulacion %> |
<%= link_to 'Back', postulacions_path %>

testBicitme/app/views/postulacions/index.html.erb
 

<h1>Listado de Postulaciones</h1>

<table>
  <thead>
    <tr>
      <th>Post tiempo taller</th>
      <th>Post referencia 1</th>
      <th>Post referencia 2</th>
      <th>Post estado</th>
      <th>Encargado</th>
      <th>Administrador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postulacions.each do |postulacion| %>
      <tr>
        <td><%= postulacion.post_tiempo_taller %></td>
        <td><%= postulacion.post_referencia_1 %></td>
        <td><%= postulacion.post_referencia_2 %></td>
        <td><%= postulacion.post_estado %></td>
        <td><%= postulacion.encargado_id %></td>
        <td><%= postulacion.administrador_id %></td>
        <td><%= link_to 'Mostrar', postulacion %></td>
        <td><%= link_to 'Responder', edit_postulacion_path(postulacion) %></td>
        <td><%= link_to 'Destruir', postulacion, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Postulacion', new_postulacion_path %>-->

testBicitme/app/views/postulacions/new.html.erb
<h1>New Postulacion</h1>

<%= render 'form' %>

<%= link_to 'Back', postulacions_path %>

testBicitme/app/views/postulacions/show.html.erb
 

<p>
  <strong>Post tiempo taller:</strong>
  <%= @postulacion.post_tiempo_taller %>
</p>

<p>
  <strong>Post referencia 1:</strong>
  <%= @postulacion.post_referencia_1 %>
</p>

<p>
  <strong>Post referencia 2:</strong>
  <%= @postulacion.post_referencia_2 %>
</p>

<p>
  <strong>Post estado:</strong>
  <%= @postulacion.post_estado %>
</p>
<!--
<p>
  <strong>Encargado:</strong>
  <%= @postulacion.encargado_id %>
</p>

<p>
  <strong>Administrador:</strong>
  <%= @postulacion.administrador_id %>
</p>

<%= link_to 'Edit', edit_postulacion_path(@postulacion) %> |-->
<%= link_to 'Ir a pagina principal', root_path %>